import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { AlertsComponent } from './components/alerts/alerts.component';
import { AccordionComponent } from './components/accordion/accordion.component';
import { BadgesComponent } from './components/badges/badges.component';
import { BreadcrumbsComponent } from './components/breadcrumbs/breadcrumbs.component';
import { ButtonsComponent } from './components/buttons/buttons.component';
import { CardsComponent } from './components/cards/cards.component';
import { CarouselComponent } from './components/carousel/carousel.component';
import { ChartsApexchartsComponent } from './components/charts-apexcharts/charts-apexcharts.component';
import { ChartsChartjsComponent } from './components/charts-chartjs/charts-chartjs.component';
import { FormsEditorsComponent } from './components/forms-editors/forms-editors.component';
import { FormsElementsComponent } from './components/forms-elements/forms-elements.component';
import { FormsLayoutsComponent } from './components/forms-layouts/forms-layouts.component';
import { IconsBootstrapComponent } from './components/icons-bootstrap/icons-bootstrap.component';
import { IconsBoxiconsComponent } from './components/icons-boxicons/icons-boxicons.component';
import { IconsRemixComponent } from './components/icons-remix/icons-remix.component';
import { ListGroupComponent } from './components/list-group/list-group.component';
import { ModalComponent } from './components/modal/modal.component';
import { PaginationComponent } from './components/pagination/pagination.component';
import { ProgressComponent } from './components/progress/progress.component';
import { SpinnersComponent } from './components/spinners/spinners.component';
import { TablesDataComponent } from './components/tables-data/tables-data.component';
import { TablesGeneralComponent } from './components/tables-general/tables-general.component';
import { TabsComponent } from './components/tabs/tabs.component';
import { TooltipsComponent } from './components/tooltips/tooltips.component';
import { PagesBlankComponent } from './pages/pages-blank/pages-blank.component';
import { PagesContactComponent } from './pages/pages-contact/pages-contact.component';
import { PagesError404Component } from './pages/pages-error404/pages-error404.component';
import { PagesFaqComponent } from './pages/pages-faq/pages-faq.component';
import { PagesLoginComponent } from './pages/pages-login/pages-login.component';
import { PagesRegisterComponent } from './pages/pages-register/pages-register.component';
import { UsersProfileComponent } from './pages/users-profile/users-profile.component';
import { ProductComponent } from './pages/product/product.component';
import { AddProductComponent } from './pages/add-product/add-product.component';
import { TotalOrdersComponent } from './pages/total-orders/total-orders.component';
import { CompletedOredersComponent } from './pages/completed-oreders/completed-oreders.component';
import { PendingOrdersComponent } from './pages/pending-orders/pending-orders.component';
import { RejectedOrdersComponent } from './pages/rejected-orders/rejected-orders.component';
import { CategoryComponent } from './pages/category/category.component';
import { SubCategoryComponent } from './pages/sub-category/sub-category.component';
import { AddSubCategoryComponent } from './pages/add-sub-category/add-sub-category.component';
import { ViewOnlinePaymentsComponent } from './pages/view-online-payments/view-online-payments.component';
import { ViewCashPaymentsComponent } from './pages/view-cash-payments/view-cash-payments.component';
import { DeliveryBoysComponent } from './pages/delivery-boys/delivery-boys.component';
import { ViewCashRecivedFromDeliveryBoyComponent } from './pages/view-cash-recived-from-delivery-boy/view-cash-recived-from-delivery-boy.component';
import { InstantOrderStatusComponent } from './pages/instant-order-status/instant-order-status.component';
import { DeliveryPincodeComponent } from './pages/delivery-pincode/delivery-pincode.component';
import { BannersComponent } from './pages/banners/banners.component';
import { VendorListComponent } from './pages/vendor-list/vendor-list.component';

const routes: Routes = [
  { path: '', component: DashboardComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'alerts', component: AlertsComponent },
  { path: 'accordion', component: AccordionComponent },
  { path: 'badges', component: BadgesComponent },
  { path: 'breadcrumbs', component: BreadcrumbsComponent },
  { path: 'buttons', component: ButtonsComponent },
  { path: 'cards', component: CardsComponent },
  { path: 'carousel', component: CarouselComponent },
  { path: 'charts-apexcharts', component: ChartsApexchartsComponent },
  { path: 'charts-chartjs', component: ChartsChartjsComponent },
  { path: 'form-editors', component: FormsEditorsComponent },
  { path: 'form-elements', component: FormsElementsComponent },
  { path: 'form-layouts', component: FormsLayoutsComponent },
  { path: 'icons-bootstrap', component: IconsBootstrapComponent },
  { path: 'icons-boxicons', component: IconsBoxiconsComponent },
  { path: 'icons-remix', component: IconsRemixComponent },
  { path: 'list-group', component: ListGroupComponent },
  { path: 'modal', component: ModalComponent },
  { path: 'pagination', component: PaginationComponent },
  { path: 'progress', component: ProgressComponent },
  { path: 'spinners', component: SpinnersComponent },
  { path: 'tables-data', component: TablesDataComponent },
  { path: 'tables-general', component: TablesGeneralComponent },
  { path: 'tabs', component: TabsComponent },
  { path: 'tooltips', component: TooltipsComponent },
  { path: 'pages-blank', component: PagesBlankComponent },
  { path: 'pages-contact', component: PagesContactComponent },
  { path: 'pages-error404', component: PagesError404Component },
  { path: 'pages-faq', component: PagesFaqComponent },
  { path: 'pages-login', component: PagesLoginComponent },
  { path: 'pages-register', component: PagesRegisterComponent },
  { path: 'user-profile', component: UsersProfileComponent },
  { path: 'products', component: ProductComponent },
  { path: 'add-product', component: AddProductComponent },
  { path: 'total-orders', component: TotalOrdersComponent },
  { path: 'completed-orders', component: CompletedOredersComponent },
  { path: 'pending-orders', component: PendingOrdersComponent },
  { path: 'rejected-orders', component: RejectedOrdersComponent },
  { path: 'category', component: CategoryComponent },
  { path: 'sub-category', component: SubCategoryComponent },
  { path: 'add-sub-category', component: AddSubCategoryComponent },
  { path: 'view-online-payments', component: ViewOnlinePaymentsComponent },
  { path: 'view-cash-payments', component: ViewCashPaymentsComponent },
  { path: 'delivery-boys', component: DeliveryBoysComponent },
  { path: 'view-cash-recived-from-delivery-boy', component: ViewCashRecivedFromDeliveryBoyComponent },
  { path: 'instant-order-status', component: InstantOrderStatusComponent },
  { path: 'delivery-pincode', component: DeliveryPincodeComponent },
  { path: 'banners', component: BannersComponent },
  { path: 'vendor-list', component: VendorListComponent },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
